### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by MGRevol** [tlagmltjq11/SWAT_UnityProject#1]
hello, i hope you doing well, the project is just crashing  after i hit play! 
can you figure out what's the reason?
i'm using unity 2019.4.8f1.

**Comment by tlagmltjq11** [comment]
Can you explain in more detail what part of the error is causing the error? 
-----Original Message-----

**Comment by MGRevol** [comment]
Hello! 
i fixed the problem by removing the sprite atlas because it makes the game crash while packing sprite atlas. 
btw, i am working on the project to make the entry team ai and the doors interactions ( door breaching, pick locks ect)

**Comment by tlagmltjq11** [comment]
Oh, I see. I hope the project goes well. And thank you so much for playing my project.
-----Original Message-----
